### ISSUE TITLE
SubmitReportState test fails when calling ky to submit report

### ISSUE THREAD

**Issue by cafca** [FixMyBerlin/fixmy.frontend#590]
The ReportDialog test "dispatches SUBMIT_REPORT_PENDING, json-schema validates a report and dispatches SUBMIT_REPORT_COMPLETE for a valid new report item" fails when trying to submit a report. 

By adding a statement to rethrow the error caught in [the submit handler](https://github.com/FixMyBerlin/fixmy.frontend/blob/develop/src/pages/Reports/apiservice.js#L25) the source of the error in ky becomes visible:

```
TypeError: Right-hand side of 'instanceof' is not an object
        at new Ky (/Users/work/code/fixmy.frontend/node_modules/ky/umd.js:240:14)
        at ky (/Users/work/code/fixmy.frontend/node_modules/ky/umd.js:500:34)
        at handleSubmitRequest$ (/Users/work/code/fixmy.frontend/src/pages/Reports/apiservice.js:18:24)
        at tryCatch (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:45:40)
        at Generator.invoke [as _invoke] (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:271:22)
        at Generator.prototype.(anonymous function) [as next] (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:97:21)
        at tryCatch (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:45:40)
        at invoke (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:135:20)
        at /Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:170:11
        at new Promise (<anonymous>)
        at callInvokeWithMethodAndArg (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:169:16)
        at AsyncIterator.enqueue (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:192:13)
        at AsyncIterator.prototype.(anonymous function) [as next] (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:97:21)
        at Object.<anonymous>.exports.async (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:216:14)
        at handleSubmitRequest (/Users/work/code/fixmy.frontend/src/pages/Reports/apiservice.js:10:1)
        at handleSubmitRequest (/Users/work/code/fixmy.frontend/src/pages/Reports/apiservice.js:47:10)
        at tryCatch (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:45:40)
        at Generator.invoke [as _invoke] (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:271:22)
        at Generator.prototype.(anonymous function) [as next] (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:97:21)
        at tryCatch (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:45:40)
        at invoke (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:135:20)
        at /Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:170:11
        at new Promise (<anonymous>)
        at callInvokeWithMethodAndArg (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:169:16)
        at AsyncIterator.enqueue (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:192:13)
        at AsyncIterator.prototype.(anonymous function) [as next] (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:97:21)
        at Object.<anonymous>.exports.async (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:216:14)
        at apiSubmitReport (/Users/work/code/fixmy.frontend/src/pages/Reports/apiservice.js:46:8)
        at _callee4$ (/Users/work/code/fixmy.frontend/src/pages/Reports/state/SubmitReportState.js:182:35)
        at tryCatch (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:45:40)
        at Generator.invoke [as _invoke] (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:271:22)
        at Generator.prototype.(anonymous function) [as next] (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:97:21)
        at tryCatch (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:45:40)
        at invoke (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:135:20)
        at /Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:170:11
        at new Promise (<anonymous>)
        at callInvokeWithMethodAndArg (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:169:16)
        at AsyncIterator.enqueue (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:192:13)
        at AsyncIterator.prototype.(anonymous function) [as next] (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:97:21)
        at Object.<anonymous>.exports.async (/Users/work/code/fixmy.frontend/node_modules/regenerator-runtime/runtime.js:216:14)
        at _callee4 (/Users/work/code/fixmy.frontend/src/pages/Reports/state/SubmitReportState.js:175:30)
        at Object.dispatch (/Users/work/code/fixmy.frontend/node_modules/redux-thunk/lib/index.js:11:18)
        at Object.dispatch (/Users/work/code/fixmy.frontend/src/pages/Reports/state/tests/SubmitReportState.unit.test.js:364:22)
        at Object.asyncJestTest (/Users/work/code/fixmy.frontend/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:102:37)
        at resolve (/Users/work/code/fixmy.frontend/node_modules/jest-jasmine2/build/queueRunner.js:43:12)
        at new Promise (<anonymous>)
        at mapper (/Users/work/code/fixmy.frontend/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at promise.then (/Users/work/code/fixmy.frontend/node_modules/jest-jasmine2/build/queueRunner.js:73:41)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

This error is only occuring in the test and not when submitting a report in the app.

The setup code of the test is using fetchMock to mock an api call. Is fetchMock compatible with ky? Could this be the cause of the error?

**Comment by cafca** [comment]
Fixed by #529
